/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.Controller_FRM_Digital_Library;
/**
 *
 * @author JorgeIgnacio
 */
public class GUI_Book extends javax.swing.JPanel {

    Controller_FRM_Digital_Library controller_FRM_Digital_Library;
    /**
     * Creates new form GUI_Book
     */
    public GUI_Book() {
        initComponents();
    }
    
    public void addController(Controller_FRM_Digital_Library controller_FRM_Digital_Library) {
        this.controller_FRM_Digital_Library=controller_FRM_Digital_Library;
        this.jB_Add.addActionListener(controller_FRM_Digital_Library);
        this.jB_ConsultBook.addActionListener(controller_FRM_Digital_Library);
        this.jB_Delete.addActionListener(controller_FRM_Digital_Library);
        this.jB_Modify.addActionListener(controller_FRM_Digital_Library);
        this.jB_Update.addActionListener(controller_FRM_Digital_Library);
    }
    
    public String[] getInformationBook() {
        String vectorBook[] = new String[4];
        vectorBook[0] = this.jT_idBook.getText();
        vectorBook[1] = this.jT_NameBook.getText();
        vectorBook[2] = this.jT_Author.getText();
        vectorBook[3] = this.jT_Title.getText();
        vectorBook[4] = this.jT_Cathegory.getText();
        return vectorBook;
    }
    
    public String getIdBook() {
        return this.jT_idBook.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_idBook = new javax.swing.JLabel();
        jT_idBook = new javax.swing.JTextField();
        jB_ConsultBook = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jT_NameBook = new javax.swing.JTextField();
        jL_Author = new javax.swing.JLabel();
        jT_Author = new javax.swing.JTextField();
        jL_Title = new javax.swing.JLabel();
        jT_Title = new javax.swing.JTextField();
        jL_Cathegory = new javax.swing.JLabel();
        jT_Cathegory = new javax.swing.JTextField();
        jB_Add = new javax.swing.JButton();
        jB_Modify = new javax.swing.JButton();
        jB_Delete = new javax.swing.JButton();
        jB_Update = new javax.swing.JButton();

        jL_idBook.setText("ID-BOOK");

        jB_ConsultBook.setText("CONSULT");

        jLabel1.setText("NAME");

        jL_Author.setText("AUTHOR");

        jL_Title.setText("TITLE");

        jL_Cathegory.setText("CATHEGORY");

        jB_Add.setText("ADD");

        jB_Modify.setText("MODIFY");

        jB_Delete.setText("DELETE");

        jB_Update.setText("UPDATE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jL_idBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jL_Title))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jT_NameBook, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jL_Author))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jT_idBook, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jB_ConsultBook)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jT_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jL_Cathegory)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT_Cathegory, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(jT_Author)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jB_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB_Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_idBook)
                    .addComponent(jT_idBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_ConsultBook))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jT_NameBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Author)
                    .addComponent(jT_Author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Title)
                    .addComponent(jT_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Cathegory)
                    .addComponent(jT_Cathegory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Add)
                    .addComponent(jB_Delete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Modify)
                    .addComponent(jB_Update))
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Add;
    private javax.swing.JButton jB_ConsultBook;
    private javax.swing.JButton jB_Delete;
    private javax.swing.JButton jB_Modify;
    private javax.swing.JButton jB_Update;
    private javax.swing.JLabel jL_Author;
    private javax.swing.JLabel jL_Cathegory;
    private javax.swing.JLabel jL_Title;
    private javax.swing.JLabel jL_idBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jT_Author;
    private javax.swing.JTextField jT_Cathegory;
    private javax.swing.JTextField jT_NameBook;
    private javax.swing.JTextField jT_Title;
    private javax.swing.JTextField jT_idBook;
    // End of variables declaration//GEN-END:variables
}
